#!/usr/bin/env python2.7

''' Primary function for mpathic.ools. Currently supports: 

simulate_library
simulate_sublib
simulate_sort
simulate_selection
simulate_mpra
'''

# run this from ./MPAthic/mpathic
# 1 python scripts/mpathic evaluate_model -m MPAthic_tests/input/model_crp_mat.txt -i MPAthic_tests/input/dataset_crp_head.txt
# 2 python scripts/mpathic evaluate_model -m MPAthic_tests/input/model_crp_nbr.txt -i MPAthic_tests/input/dataset_crp_head.txt


# why do things end up here?
#/Library/Python/2.7/site-packages/src-0.1.13-py2.7-macosx-10.12-intel.egg/src


from __future__ import division
import numpy as np
import scipy as sp
import argparse
import sys
import csv

# mpathic only works at the commandline
assert __name__ == '__main__'

# Create argparse parser. 
parser = argparse.ArgumentParser()

# All functions can specify and output file. Default is stdout.
parser.add_argument('-o','--out',default=False,help='Output location/type, by default it writes to standard output, if a file name is supplied it will write to a text file')

# Add various subcommands individually viva subparsers
subparsers = parser.add_subparsers()

#sys.path.insert(0,'/Users/tareen/Desktop/MPAthic/MPAthic_virtual_env_py_2/mpathic/src')
sys.path.append('./src')

#import sortseq_for_doc
import sortseq_for_doc

#import sortseq_for_doc as sortseq_for_doc

import run_tests as run_tests
run_tests.add_subparser(subparsers)

import draw as draw
draw.add_subparser(subparsers)

import evaluate_model as evaluate_model
evaluate_model.add_subparser(subparsers)

import preprocess as preprocess
preprocess.add_subparser(subparsers)

import learn_model as learn_model
learn_model.add_subparser(subparsers)

import profile_ct as profile_ct
profile_ct.add_subparser(subparsers)

import profile_mut as profile_mut
profile_mut.add_subparser(subparsers)

import profile_info as profile_info
profile_info.add_subparser(subparsers)

import profile_freq as profile_freq
profile_freq.add_subparser(subparsers)

import predictiveinfo as predictiveinfo
predictiveinfo.add_subparser(subparsers)

import simulate_library as simulate_library
simulate_library.add_subparser(subparsers)

import simulate_sort as simulate_sort
simulate_sort.add_subparser(subparsers)

import simulate_expression as simulate_expression
simulate_expression.add_subparser(subparsers)


import validate as validate
validate.add_subparser(subparsers)

import scan_model as scan_model
scan_model.add_subparser(subparsers)

print('Loaded imports for MPathic successfully')

# Final incantiation needed for this to work
args = parser.parse_args()
args.func(args=args)









